# Pandas 

In [1]:
import pandas as pd

# there are 2 objects 1) Series 2) Data Frame
* for single dimension then series
* for multiple dimension then data frame

# 1) Series 

In [5]:
obj = pd.Series([4,5,-4,7])
print(obj)

0    4
1    5
2   -4
3    7
dtype: int64


In [6]:
obj = pd.Series([[4,5,-4,7],[4,5,-4,7]])
print(obj)

0    [4, 5, -4, 7]
1    [4, 5, -4, 7]
dtype: object


In [7]:
obj = pd.Series([[4,5,-4,7],[4,5,-4,7],[4,5,-4,7]])
print(obj)

0    [4, 5, -4, 7]
1    [4, 5, -4, 7]
2    [4, 5, -4, 7]
dtype: object


In [9]:
obj = pd.Series([4,5,-4,7])
print(obj)
print(obj.values)
print(obj.index)

0    4
1    5
2   -4
3    7
dtype: int64
[ 4  5 -4  7]
RangeIndex(start=0, stop=4, step=1)


In [11]:
sales = pd.Series([4999,5778,4555,2215], index=['jan','feb','mar','apr']) # index and values should be the same
print(sales.values)
print(sales.index)

[4999 5778 4555 2215]
Index(['jan', 'feb', 'mar', 'apr'], dtype='object')


In [16]:
sandwitch = pd.Series([43,57,45,22,55,55,0], index=['mon','tue','wed','thr','fri','sat','sun']) # index and values should be the same
print(sandwitch)
print(sandwitch.values)
print(sandwitch.index)

mon    43
tue    57
wed    45
thr    22
fri    55
sat    55
sun     0
dtype: int64
[43 57 45 22 55 55  0]
Index(['mon', 'tue', 'wed', 'thr', 'fri', 'sat', 'sun'], dtype='object')


In [29]:
sandwitch = pd.Series([43,57,45,22,55,55,0], index=range(0,7)) # index and values should be the same
print(sandwitch)
print(sandwitch.values)
print(sandwitch.index)

0    43
1    57
2    45
3    22
4    55
5    55
6     0
dtype: int64
[43 57 45 22 55 55  0]
RangeIndex(start=0, stop=7, step=1)


In [42]:
import calendar as cal
sandwitch = pd.Series([43,57,45,22,55,55,0], index=[cal.month_name[i] for i in range(1,8)])  # index and values should be the same
print(sandwitch)
print(sandwitch.values)
print(sandwitch.index)

January     43
February    57
March       45
April       22
May         55
June        55
July         0
dtype: int64
[43 57 45 22 55 55  0]
Index(['January', 'February', 'March', 'April', 'May', 'June', 'July'], dtype='object')


In [36]:
print(sandwitch)
print(sandwitch[3:4])

0    43
1    57
2    45
3    22
4    55
5    55
6     0
dtype: int64
3    22
dtype: int64


In [43]:
sdata ={"Sindh":35000,  "Punjab": 45000 , "KPK":6000, "Balochistan":8000 } #converting dictionery into series
tax_by_state = pd.Series(sdata, index =["Punjab","Sindh","KPK","Balochistan","GB","NWFP"]) # you can change the sequence as well
print (tax_by_state)
print (pd.isnull(tax_by_state))

Punjab         45000.0
Sindh          35000.0
KPK             6000.0
Balochistan     8000.0
GB                 NaN
NWFP               NaN
dtype: float64
Punjab         False
Sindh          False
KPK            False
Balochistan    False
GB              True
NWFP            True
dtype: bool


In [49]:
sandwitch = pd.Series([43,57,45,0,55,0,0], index=['mon','tue','wed','thr','fri','sat','sun']) # index and values should be the same
print(sandwitch)
sandwitch.index = ["m","t","w","t","f","s","s","r"] # only while convertion from dictionary the NaN will be added otherwsie no
print(sandwitch)


mon    43
tue    57
wed    45
thr     0
fri    55
sat     0
sun     0
dtype: int64


ValueError: Length mismatch: Expected axis has 7 elements, new values have 8 elements

# 2) Dataframe 

# - Data frame represent a rectangular table of data ; row and column has names/lables ; data maangement is done in pandas and       when we run machine learning then we pcik some part from panda array and store in numpy for giving it to machine learning algo.

- Machine learning only wants data in a numpy array no need of index / lables for ML algos. Also for numpy array individual elements are not important and mostly we apply functions on the entire array e.g. pixels of a photo. but in pandas we get dataset where individaul elements are important and we apply filters base on that.

- dataframe is a combination of series ... two series with same index can be merged 
- Read Chapter 5 of the book
- behind the scene Numpy is working on case of Pandas as well.
- Pandas also stores data in a continuous series of memory slots.
- if very large data that panda will not store it then we need list as list stores in seperate locations
* DATA TYPE IS NOT AN OBJECT 
- all these part of evolution for getting imporvements i.e first python is invented then list > dictionery > tuples/sets > numpy > pandas   .... all are imporved and sort out problems of the previous versions.
- chapter 4 and appendex A2 for quiz




# apples = pd.Series ([3,2,7,0])
oranges = pd.Series ([4,5,9,3])

data= {"apples":apples, "oranges":oranges}
fruits_df = pd.DataFrame(data)
print(fruits_df)


In [3]:
apples = pd.Series ([3,2,7,0], index =[1,2,3,4])
oranges = pd.Series ([4,5,9,3])

data= {"apples":apples, "oranges":oranges}
fruits_df = pd.DataFrame(data)
print(fruits_df)

   apples  oranges
0     NaN      4.0
1     3.0      5.0
2     2.0      9.0
3     7.0      3.0
4     0.0      NaN


In [4]:
state = ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada']
data = {'state':state,
       'year' :[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
       }
state_pop_df =pd.DataFrame (data, index =['1st','2nd','3rd','4th','5th','6th'])
print(state_pop_df)

      state  year  pop
1st    Ohio  2000  1.5
2nd    Ohio  2001  1.7
3rd    Ohio  2002  3.6
4th  Nevada  2001  2.4
5th  Nevada  2002  2.9
6th  Nevada  2003  3.2


In [8]:
state_pop_df =pd.DataFrame (data, columns =['Year','state','pop','year'])
state_pop_df.head(2)

Year state  pop  year
0  NaN  Ohio  1.5  2000
1  NaN  Ohio  1.7  2001

In [11]:
state_pop_df =pd.DataFrame (data, columns =['Year','state','pop','year'],index =['one','two','three','four','five','six'])
state_pop_df.head(10)

Year   state  pop  year
one    NaN    Ohio  1.5  2000
two    NaN    Ohio  1.7  2001
three  NaN    Ohio  3.6  2002
four   NaN  Nevada  2.4  2001
five   NaN  Nevada  2.9  2002
six    NaN  Nevada  3.2  2003

In [12]:
state_pop_df["year"] # dictionery style access of field

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [13]:
state_pop_df.year  # attribute style access of field

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [14]:
state_pop_df["year"]= 2020 # updating field
state_pop_df.head()

Year   state  pop  year
one    NaN    Ohio  1.5  2020
two    NaN    Ohio  1.7  2020
three  NaN    Ohio  3.6  2020
four   NaN  Nevada  2.4  2020
five   NaN  Nevada  2.9  2020

In [15]:
state_pop_df

Year   state  pop  year
one    NaN    Ohio  1.5  2020
two    NaN    Ohio  1.7  2020
three  NaN    Ohio  3.6  2020
four   NaN  Nevada  2.4  2020
five   NaN  Nevada  2.9  2020
six    NaN  Nevada  3.2  2020

In [18]:
import numpy as np
ln = len(state_pop_df)
rng = np.arange(ln)
print(rng)

[0 1 2 3 4 5]


In [19]:
state_pop_df['year']=rng

In [20]:
state_pop_df

Year   state  pop  year
one    NaN    Ohio  1.5     0
two    NaN    Ohio  1.7     1
three  NaN    Ohio  3.6     2
four   NaN  Nevada  2.4     3
five   NaN  Nevada  2.9     4
six    NaN  Nevada  3.2     5

In [26]:
S =pd.Series ([2000,2001,2002,2001,2002,2003],index =['one','two','three','four','five','six'])
state_pop_df.year = S 
print(state_pop_df)

      Year   state  pop  year
one    NaN    Ohio  1.5  2000
two    NaN    Ohio  1.7  2001
three  NaN    Ohio  3.6  2002
four   NaN  Nevada  2.4  2001
five   NaN  Nevada  2.9  2002
six    NaN  Nevada  3.2  2003


# Reindexing - changing number of rows and columns 

In [31]:
obj = pd.Series (['blue','white','green'], index = [0,4,6])
print(obj)
obj= obj.reindex(range(9))
print(obj)

0     blue
4    white
6    green
dtype: object
0     blue
1      NaN
2      NaN
3      NaN
4    white
5      NaN
6    green
7      NaN
8      NaN
dtype: object


In [32]:
obj = pd.Series (['blue','white','green'], index = [0,4,6])
print(obj)
obj= obj.reindex(range(9),method='ffill') # fill the last values onwards i.e forward fill
print(obj)

0     blue
4    white
6    green
dtype: object
0     blue
1     blue
2     blue
3     blue
4    white
5    white
6    green
7    green
8    green
dtype: object


In [33]:
obj = pd.Series (['blue','white','green'], index = [0,4,6])
print(obj)
obj= obj.reindex(range(9),method='bfill') # fill the last values onwards i.e forward fill
print(obj)

0     blue
4    white
6    green
dtype: object
0     blue
1    white
2    white
3    white
4    white
5    green
6    green
7      NaN
8      NaN
dtype: object


In [50]:
states = pd.DataFrame(np.arange(9).reshape(3,3) , index =['a','b','c'], columns =['Ohio','Texas','California'])
print(states)
states_name = ['Texas','Utah','California','Ohio']

   Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8


In [51]:
states = states.reindex(columns=states_name) # reshaping columns
print(states)

   Texas  Utah  California  Ohio
a      1   NaN           2     0
b      4   NaN           5     3
c      7   NaN           8     6


In [49]:
states = states.drop('Utah', axis = 1)  # dropping a columns use axis = 1
states

Texas  California  Ohio
a      1           2     0
b      4           5     3
c      7           8     6

In [52]:
states.drop('Utah', axis = 1, inplace = True) # no need to reassign the inplace function will save the new dataframe on old data frame
states

Texas  California  Ohio
a      1           2     0
b      4           5     3
c      7           8     6

In [46]:
states = states.drop('a', axis = 0)  # dropping a row use axis = 0
states

Texas  California  Ohio
b      4           5     3
c      7           8     6

## Indexing , Selection, and filtering 

In [4]:
import numpy as np
import pandas as pd

data_df = pd.DataFrame( np.arange(16).reshape(4,4), index =['Ohio','Colorado','Utah','New York']
, columns=['one','two','three','four'] )
print(data_df)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [65]:
print (data_df [ data_df ['three'] > 6 ])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15


In [67]:
df2 = data_df [["one","three"]]; print (df2)

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14


In [68]:
print (data_df[:2])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7


In [71]:
print (data_df[2:])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15


In [72]:
print (data_df.one[2:])

Utah         8
New York    12
Name: one, dtype: int32


In [74]:
print (data_df.loc[['Colorado','Ohio'], ['two','three']] )

          two  three
Colorado    5      6
Ohio        1      2


In [78]:
print (data_df.iloc[:] )

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


print (data_df.iloc[2:] )

In [81]:
print (data_df.iloc[2:][1:] )

          one  two  three  four
New York   12   13     14    15


In [82]:
print(list("abcd"))

['a', 'b', 'c', 'd']


# Arithmatic opearions on Dataframes

In [34]:
import numpy as np
import pandas as pd

df1 =  pd.DataFrame( np.arange(16).reshape(4,4), index =['Ohio','Colorado','Utah','New York'] 
                  , columns= list("abcd")  #columns=['one','two','three','four']  
                   )
print(df1)

# data_df = pd.DataFrame( np.arange(16).reshape(4,4), index =['Ohio','Colorado','Utah','New York']
# , columns=['one','two','three','four'] )

           a   b   c   d
Ohio       0   1   2   3
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15


# loading data

In [1]:
import pandas as pd
sample_df= pd.read_csv("sample.csv")
print (sample_df)
print("\n")

  studentid         name   chimestry   physics   english   math
0       A01     arif ali          20        30        40     50
1       A02  kamran khan          30        40        50     60
2       A03   imran ali           40        50        60     70
3       A04  kashif khan          50        60        70     80




In [2]:
print(sample_df[:2])

  studentid         name   chimestry   physics   english   math
0       A01     arif ali          20        30        40     50
1       A02  kamran khan          30        40        50     60


In [16]:
sample_df= pd.read_csv("sample.csv",skiprows =1, names=['id','name','ch','ph','en','math'])
print (sample_df)
print("\n")

    id         name  ch  ph  en  math
0  A01     arif ali  20  30  40    50
1  A02  kamran khan  30  40  50    60
2  A03   imran ali   40  50  60    70
3  A04  kashif khan  50  60  70    80




In [19]:
sample_df= pd.read_csv("examples/sample2.csv")
print (sample_df)
print("\n")
# we have to specify which column will be used  as index
parsed= pd.read_csv("examples/sample2.csv", index_col=['key1','key2']) # hierarchal index
parsed

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16




value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [21]:
sample_df= pd.read_csv("examples/sample3.csv")
print (sample_df)
sentinels = {'message':['foo','NA']}  # marking specific values as NULL
sample_df= pd.read_csv("examples/sample3.csv",na_values=sentinels)
sample_df

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo


something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

# Reading Text File in Pieces

In [38]:
sample_df= pd.read_csv("datasets/train.csv",nrows =20)
sample_df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0             842     0          2.2         0   1       0           7    0.6   
1            1021     1          0.5         1   0       1          53    0.7   
2             563     1          0.5         1   2       1          41    0.9   
3             615     1          2.5         0   0       0          10    0.8   
4            1821     1          1.2         0  13       1          44    0.6   
5            1859     0          0.5         1   3       0          22    0.7   
6            1821     0          1.7         0   4       1          10    0.8   
7            1954     0          0.5         1   0       0          24    0.8   
8            1445     1          0.5         0   0       0          53    0.7   
9             509     1          0.6         1   2       1           9    0.1   
10            769     1          2.9         1   0       0           9    0.1   
11           1520     1          2.2         0   5       1          33    0.5   
12           1815     0          2.8         0   2       0          33    0.6   
13            803     1          2.1         0   7       0          17    1.0   
14           1866     0          0.5         0  13       1          52    0.7   
15            775     0          1.0         0   3       0          46    0.7   
16            838     0          0.5         0   1       1          13    0.1   
17            595     0          0.9         1   7       1          23    0.1   
18           1131     1          0.5         1  11       0          49    0.6   
19            682     1          0.5         0   4       0          19    1.0   

    mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0         188        2  ...         20       756  2549     9     7         19   
1         136        3  ...        905      1988  2631    17     3          7   
2         145        5  ...       1263      1716  2603    11     2          9   
3         131        6  ...       1216      1786  2769    16     8         11   
4         141        2  ...       1208      1212  1411     8     2         15   
5         164        1  ...       1004      1654  1067    17     1         10   
6         139        8  ...        381      1018  3220    13     8         18   
7         187        4  ...        512      1149   700    16     3          5   
8         174        7  ...        386       836  1099    17     1         20   
9          93        5  ...       1137      1224   513    19    10         12   
10        182        5  ...        248       874  3946     5     2          7   
11        177        8  ...        151      1005  3826    14     9         13   
12        159        4  ...        607       748  1482    18     0          2   
13        198        4  ...        344      1440  2680     7     1          4   
14        185        1  ...        356       563   373    14     9          3   
15        159        2  ...        862      1864   568    17    15         11   
16        196        8  ...        984      1850  3554    10     9         19   
17        121        3  ...        441       810  3752    10     2         18   
18        101        5  ...        658       878  1835    19    13         16   
19        121        4  ...        902      1064  2337    11     1         18   

    three_g  touch_screen  wifi  price_range  
0         0             0     1            1  
1         1             1     0            2  
2         1             1     0            2  
3         1             0     0            2  
4         1             1     0            1  
5         1             0     0            1  
6         1             0     1            3  
7         1             1     1            0  
8         1             0     0            0  
9         1             0     0            0  
10        0             0     0            3  
11        1             1     1     

In [47]:
frame= pd.read_csv("datasets/train.csv")
print(len(frame))

chunks= pd.read_csv("datasets/train.csv",chunksize =600)

chunkList = []
for chunk in chunks:
    #print(type(chunk))
    #print(chunk.head())
    chunkList.append(chunk)
    
df = chunkList[2]
print(len(chunkList))
df.head()


2000
4


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1200            530     0          2.4         0   1       0          32   
1201           1481     1          2.0         1   0       0          35   
1202           1068     0          2.7         1   0       1          45   
1203           1487     0          0.5         0   6       1          57   
1204           1524     0          2.5         1  11       1          41   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
1200    0.3         88        6  ...         48      1012   959    17     7   
1201    0.5        105        3  ...        249       522  2635    17    16   
1202    0.6        194        5  ...        935      1499  1754    17     7   
1203    0.7         84        3  ...        140       768  2563    18     4   
1204    1.0         96        4  ...        184       740  1936     7     0   

      talk_time  three_g  touch_screen  wifi  price_range  
1200          6        0             1     0            0  
1201          4        1             0     1            2  
1202          9        1             0     1            1  
1203         14        1             0     0            2  
1204          9        1             1     1            1  

[5 rows x 21 columns]

In [48]:
frame= pd.read_csv("datasets/train.csv")
print(len(frame))

chunks= pd.read_csv("datasets/train.csv",nrows =20,chunksize =2)

chunkList = []
for chunk in chunks:
    #print(type(chunk))
    #print(chunk.head())
    chunkList.append(chunk)
    
df = chunkList[2]
print(len(chunkList))
df.head()


2000
10


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   

   three_g  touch_screen  wifi  price_range  
4        1             1     0            1  
5        1             0     0            1  

[2 rows x 21 columns]

In [53]:
import pandas as pd
tables =  pd.read_html('examples/fdic_failed_bank_list.html')
print(type(tables))
print(len(tables))
failures_df = tables[0]
print(type(failures_df))
print(failures_df.shape)
columns = failures_df.columns
print(failures_df.head())




<class 'list'>
1
<class 'pandas.core.frame.DataFrame'>
(547, 7)
                      Bank Name             City  ST   CERT  \
0                   Allied Bank         Mulberry  AR     91   
1  The Woodbury Banking Company         Woodbury  GA  11297   
2        First CornerStone Bank  King of Prussia  PA  35312   
3            Trust Company Bank          Memphis  TN   9956   
4    North Milwaukee State Bank        Milwaukee  WI  20364   

                 Acquiring Institution        Closing Date       Updated Date  
0                         Today's Bank  September 23, 2016  November 17, 2016  
1                          United Bank     August 19, 2016  November 17, 2016  
2  First-Citizens Bank & Trust Company         May 6, 2016  September 6, 2016  
3           The Bank of Fayette County      April 29, 2016  September 6, 2016  
4  First-Citizens Bank & Trust Company      March 11, 2016      June 16, 2016  


In [55]:
# Binary Data Formats -- fast processing open and close

frame = pd.read_csv('examples/ex1.csv')
frame.to_pickle()


TypeError: to_pickle() missing 1 required positional argument: 'path'

In [60]:
# Using HDF5 formats -- hierarchal data format(HDF) stores data in hierarchal form
# only DBMS system can manage data in file
# All the data structures e.g. list, panda dataframe , tuple, dictionery work in memory only no datafile management
# hence we need to use this functionality like pcikle, HDFS

import numpy as np
frame = pd.DataFrame({'a': np.random.randn(100),'b':np.random.randn(100)})
store = pd.HDFStore ('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
print(store)
x=store.obj1
print(type(x))
print(x.head())
print("------------------------")
store.put ('obj2',frame,format='table')   # save in table format as we can apply condition on table format
store.select ('obj2', where =['index >10 and index <=15'] )
store.close()
frame.to_hdf('mydata.h5','obj3', format = 'table')
frame= pd.read_hdf('mydata.h5','obj3',  where =['index <5'])



<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

<class 'pandas.core.frame.DataFrame'>
          a         b
0 -0.219526  0.375311
1 -0.480268 -1.209734
2 -0.665552  2.435660
3 -0.332214 -0.582487
4 -1.495500 -1.101431
------------------------


ValueError: The file 'mydata.h5' is already opened, but not in read-only mode (as requested).

In [61]:
import requests
import numpy as np
url = 'https://api.github.com/repos/pandas-dev/pandas/issues' # git hub api to load data directly
resp = requests.get(url)
print(resp)
data=resp.json()
print(type(data))
print(data)


<Response [403]>
<class 'dict'>
{'message': "API rate limit exceeded for 202.143.115.9. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}


In [ ]:
import sqlite3

query =""" CREATE TABLE test ( a varchar (20),
b varchar (20), c real,  d integer );)"""

con = sqlite3.connect ('mydata.sqlite')
con.execute(query)
con.commit()

#OR USE Sqlalchemy -- simple to read may types of databases 



In [10]:
import pandas as pd
from numpy import nan as NA

data = pd.DataFrame ([[1.,6.5,NA],[1.,NA, NA],[NA,NA, NA],[NA,6.5, NA]], columns = list('abc'))
display (data) # display function only works in jupyter notebook
cleansed= data.dropna(axis=0)
display(cleansed)

cleansed= data.dropna(axis=1)
display(cleansed)



a    b   c
0  1.0  6.5 NaN
1  1.0  NaN NaN
2  NaN  NaN NaN
3  NaN  6.5 NaN

Empty DataFrame
Columns: [a, b, c]
Index: []

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [20]:
import numpy as np
data= pd.DataFrame( np.random.randn(7,3) )
print (data)
data.iloc[:4,1] = NA
data.iloc[:2,2] = NA
display(data)

          0         1         2
0 -0.197839  0.961146 -1.801513
1  0.286475 -1.159209  0.308014
2 -0.504360  0.479777 -1.226778
3 -1.677352  0.178041  1.278613
4 -0.043797 -1.253299  0.840417
5  1.122265  0.130276  1.391111
6 -0.376752 -0.285122 -0.094730


0         1         2
0 -0.197839       NaN       NaN
1  0.286475       NaN       NaN
2 -0.504360       NaN -1.226778
3 -1.677352       NaN  1.278613
4 -0.043797 -1.253299  0.840417
5  1.122265  0.130276  1.391111
6 -0.376752 -0.285122 -0.094730

In [21]:

data=data.fillna({1:0.5,2:0 })  # filling NA with different values at different locations using dictionery

#data=data.fillna(1.5) # filling NA with values
display(data)    

0         1         2
0 -0.197839  0.500000  0.000000
1  0.286475  0.500000  0.000000
2 -0.504360  0.500000 -1.226778
3 -1.677352  0.500000  1.278613
4 -0.043797 -1.253299  0.840417
5  1.122265  0.130276  1.391111
6 -0.376752 -0.285122 -0.094730

In [22]:


import numpy as np
data= pd.DataFrame( np.random.randn(7,3) )
print (data)
data.iloc[:4,1] = NA
data.iloc[:2,2] = NA
display(data)

          0         1         2
0  0.784490 -1.650042 -1.603835
1 -0.572558  0.052929 -0.635445
2 -1.405375 -1.184368 -0.505365
3  1.254549  1.244715  1.631967
4  0.514822  0.019404  1.555349
5 -0.742123 -1.864345  0.756223
6 -1.761383 -0.794253  0.155399


0         1         2
0  0.784490       NaN       NaN
1 -0.572558       NaN       NaN
2 -1.405375       NaN -0.505365
3  1.254549       NaN  1.631967
4  0.514822  0.019404  1.555349
5 -0.742123 -1.864345  0.756223
6 -1.761383 -0.794253  0.155399

In [24]:
data = data. fillna (method = 'bfill')
print(data)

          0         1         2
0  0.784490  0.019404 -0.505365
1 -0.572558  0.019404 -0.505365
2 -1.405375  0.019404 -0.505365
3  1.254549  0.019404  1.631967
4  0.514822  0.019404  1.555349
5 -0.742123 -1.864345  0.756223
6 -1.761383 -0.794253  0.155399


In [25]:
import numpy as np
data= pd.DataFrame(  np.random.randn(7,3) )    
print (data)
data.iloc[2:4,1] = NA
data.iloc[1:2,2] = NA
display(data)

          0         1         2
0 -0.467335 -0.724848 -0.758203
1  1.810571  0.239231 -0.238070
2 -0.326739 -1.623905  1.288310
3  0.287591  0.435025 -0.761356
4  0.845641 -0.394989  0.349106
5 -1.685513  1.244036  0.454435
6  0.485986  1.511678  0.811823


0         1         2
0 -0.467335 -0.724848 -0.758203
1  1.810571  0.239231       NaN
2 -0.326739       NaN  1.288310
3  0.287591       NaN -0.761356
4  0.845641 -0.394989  0.349106
5 -1.685513  1.244036  0.454435
6  0.485986  1.511678  0.811823

In [27]:
data=data.fillna(method='ffill'); data

0         1         2
0 -0.467335 -0.724848 -0.758203
1  1.810571  0.239231 -0.758203
2 -0.326739  0.239231  1.288310
3  0.287591  0.239231 -0.761356
4  0.845641 -0.394989  0.349106
5 -1.685513  1.244036  0.454435
6  0.485986  1.511678  0.811823

In [30]:
import pandas as pd
data = pd.DataFrame ({'k1':['one','two']*3 + ['two'], 'k2':[1,1,2,4,3,4,4]})

display(data)
data.duplicated()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   4
4  one   3
5  two   4
6  two   4

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [36]:
data['v1'] = ['one','two','one','four','one','six','two']
display(data)
display(data[['k1','v1']])
display(data)
df = data.drop_duplicates(['k1','v1'])
print(df)

k1  k2    v1
0  one   1   one
1  two   1   two
2  one   2   one
3  two   4  four
4  one   3   one
5  two   4   six
6  two   4   two

k1    v1
0  one   one
1  two   two
2  one   one
3  two  four
4  one   one
5  two   six
6  two   two

k1  k2    v1
0  one   1   one
1  two   1   two
2  one   2   one
3  two   4  four
4  one   3   one
5  two   4   six
6  two   4   two

    k1  k2    v1
0  one   1   one
1  two   1   two
3  two   4  four
5  two   4   six


In [45]:
# Use replace functions for replacing all sort of values inlcuding nan

import numpy as np
data= pd.DataFrame(  np.random.randn(7,3) )    
print (data)
data.iloc[2:4,1] = NA
data.iloc[1:2,2] = NA
display(data)


          0         1         2
0 -0.460202 -0.506683  1.693315
1 -0.175969 -0.590614  0.565078
2 -0.123944 -1.116743  0.181708
3 -0.181817  0.809502  1.529746
4 -0.575344 -1.165108  1.684158
5  0.185970 -1.860690  1.503706
6 -1.871645  0.063308  0.000815


0         1         2
0 -0.460202 -0.506683  1.693315
1 -0.175969 -0.590614       NaN
2 -0.123944       NaN  0.181708
3 -0.181817       NaN  1.529746
4 -0.575344 -1.165108  1.684158
5  0.185970 -1.860690  1.503706
6 -1.871645  0.063308  0.000815

In [46]:
 data= data.replace(np.nan, -9999)
print (data)

          0            1            2
0 -0.460202    -0.506683     1.693315
1 -0.175969    -0.590614 -9999.000000
2 -0.123944 -9999.000000     0.181708
3 -0.181817 -9999.000000     1.529746
4 -0.575344    -1.165108     1.684158
5  0.185970    -1.860690     1.503706
6 -1.871645     0.063308     0.000815


In [47]:
data= data.replace(-9999, -111)
print (data)

          0           1           2
0 -0.460202   -0.506683    1.693315
1 -0.175969   -0.590614 -111.000000
2 -0.123944 -111.000000    0.181708
3 -0.181817 -111.000000    1.529746
4 -0.575344   -1.165108    1.684158
5  0.185970   -1.860690    1.503706
6 -1.871645    0.063308    0.000815


In [48]:
data= data.replace(-111, "hello")
print (data)

          0          1            2
0 -0.460202  -0.506683      1.69332
1 -0.175969  -0.590614        hello
2 -0.123944      hello     0.181708
3 -0.181817      hello      1.52975
4 -0.575344   -1.16511      1.68416
5  0.185970   -1.86069      1.50371
6 -1.871645  0.0633085  0.000814907


In [49]:
data= data.replace(["hello", -1.16511],[1,0])
print (data)

          0          1            2
0 -0.460202  -0.506683      1.69332
1 -0.175969  -0.590614            1
2 -0.123944          1     0.181708
3 -0.181817          1      1.52975
4 -0.575344   -1.16511      1.68416
5  0.185970   -1.86069      1.50371
6 -1.871645  0.0633085  0.000814907


# Detecting and filtering outliers

In [55]:
df= pd.DataFrame( np.random.randn(1000,4) )
display(df.describe())
outliers = df[(np.abs(df) >3).any(1)]  # parameters of any functions represent axis 1 for row 0 for column
print(len(outliers), len(df))


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002465    -0.013255     0.006019     0.026296
std       1.021813     1.014899     0.992234     1.019464
min      -3.215334    -2.982628    -2.516016    -3.237163
25%      -0.680538    -0.708180    -0.640024    -0.641825
50%      -0.024264    -0.021345     0.023767     0.033067
75%       0.675908     0.651456     0.647449     0.686286
max       2.784187     3.112859     3.758611     3.005728

5 1000


In [62]:
data= pd.DataFrame( np.arange(12).reshape((3,4)), index=['Ohio','Colorada','New York'] 
                   , columns =['one','two','three','four'] )
display(data)
transform = lambda row_index : row_index[:4].upper()
data.index= data.index.map(transform)
display(data)

one  two  three  four
Ohio        0    1      2     3
Colorada    4    5      6     7
New York    8    9     10    11

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

# Permutation and random sampling 

In [65]:
df = pd.DataFrame (np.arange(5*4).reshape(5,4))
sampler = np.random.permutation(4)   # permutation generates some random values
print(sampler)
display(df)
df.take(sampler)

[0 3 1 2]


0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

# Regular Expression

In [67]:
import re 
text="foo   bar\t baz \tqux"
display(text.split(" "))          # using normar split 
display(re.split ('\s+',text))    # using regular expression ;    s+ means white spaces one or more or tab i.e. \t

['foo', '', '', 'bar\t', 'baz', '\tqux']

['foo', 'bar', 'baz', 'qux']